name: codecov.io

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
              gcc \
              acl \
              libacl1-dev \
              attr \
              libcap2-bin \
              libcap-dev \
              libonig-dev \
              liburing-dev

      - name: Generate coverage
        run: |
          ./configure --enable-gcov EXTRA_CFLAGS="-std=gnu2x"
          make -j$(nproc) check TEST_FLAGS="--sudo"
          gcov -abcfpu obj/*/*.o

      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
